# permissions for end users to view multiclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: multicluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-vip-multi-cluster
    app.kubernetes.io/part-of: kube-vip-multi-cluster
    app.kubernetes.io/managed-by: kustomize
  name: multicluster-viewer-role
rules:
- apiGroups:
  - kube-vip.io
  resources:
  - multiclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kube-vip.io
  resources:
  - multiclusters/status
  verbs:
  - get
