---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kube-vip.io
  resources:
  - multiclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-vip.io
  resources:
  - multiclusters/finalizers
  verbs:
  - update
- apiGroups:
  - kube-vip.io
  resources:
  - multiclusters/status
  verbs:
  - get
  - patch
  - update
